### ISSUE TITLE
Incompatible Project

### ISSUE THREAD

**Issue by zorbagtamangen** [riganti/dotvvm-samples-checkbook#2]
I have run your dotvvm sample project but got project incompatible issue. I tried to load in VS 2015 & 2013 but no luck.

![checkbook incompatible](https://cloud.githubusercontent.com/assets/19919334/16028294/7d71977c-3210-11e6-9362-233b4c790602.png)

Thanks,Z

**Comment by quigamdev** [comment]
Hi, do you have installed DotVVM extension for Visual Studio 2015? DotVVM has extension that inserts a specific ProjectType guid into csproj. That makes project incompatible. 

The extension provides you IntelliSense, project and items templates and much more.

DotVVM Extension is available at https://www.dotvvm.com/landing/dotvvm-for-visual-studio-extension

**Comment by zorbagtamangen** [comment]
Hi,
I have install the dotvvm using nuget cmd ("Install-Package DotVVM -Pre")only since I don’t have admin rights to install non-standard software in my work machine.

I would appreciate if you have installer that doesn’t required administrator rights?

Thanks/Regards, Z

**Comment by quigamdev** [comment]
I'm sorry. Currently we are not able to add extension to Visual Studio without administration permissions.
